name: easy_os_mobile
description: "A new Flutter project."
publish_to: 'none' 

version: 1.0.0+1

environment:
  sdk: ^3.7.2

dependencies:
  flutter:
    sdk: flutter
  
  cupertino_icons: ^1.0.8
  http: ^1.3.0
  flutter_dotenv: ^5.2.1
  json_annotation: ^4.9.0
  logger: ^2.5.0
  flutter_secure_storage: ^9.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0
  json_serializable: ^6.9.5
  build_runner: ^2.4.15
  flutter_launcher_icons: ^0.13.1

flutter_icons:
  android: true
  ios: true
  image_path: "assets/logo/logo.png"

flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/logo/logo.png

  fonts:
    - family: Mona_Sans
      fonts:
        - asset: assets/fonts/Mona_Sans,Work_Sans/Mona_Sans/static/MonaSans-Medium.ttf
        
    - family: Work_Sans
      fonts:
        - asset: assets/fonts/Mona_Sans,Work_Sans/Work_Sans/static/WorkSans-Regular.ttf
